controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

tasks:
        path: /tareas
        controller: App\Controller\TaskController::index

my_task:
        path: /mis_tareas
        controller: App\Controller\TaskController::myTasks
        
task_detail:
        path: /tarea/{id}
        controller: App\Controller\TaskController::detail

task_creation:
        path: /crear-tarea
        controller: App\Controller\TaskController::creation

task_edit:
        path: editar-tarea/{id}
        controller: App\Controller\TaskController::edit

task_delete:
        path: borrar-tarea/{id}
        controller: App\Controller\TaskController::delete

register:
        path: /registro
        controller: App\Controller\UserController::register

login:
        path: /
        controller: App\Controller\UserController::login

logout:
        path: /logout
        controller: App\Controller\UserController::logout
